package com.yuzhi.ainms.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CountryStisticsAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCountryStisticsAllPropertiesEquals(
    CountryStistics expected,
    CountryStistics actual
  ) {
    assertCountryStisticsAutoGeneratedPropertiesEquals(expected, actual);
    assertCountryStisticsAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCountryStisticsAllUpdatablePropertiesEquals(
    CountryStistics expected,
    CountryStistics actual
  ) {
    assertCountryStisticsUpdatableFieldsEquals(expected, actual);
    assertCountryStisticsUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCountryStisticsAutoGeneratedPropertiesEquals(
    CountryStistics expected,
    CountryStistics actual
  ) {
    assertThat(expected)
      .as("Verify CountryStistics auto generated properties")
      .satisfies(
        e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId())
      );
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCountryStisticsUpdatableFieldsEquals(
    CountryStistics expected,
    CountryStistics actual
  ) {
    assertThat(expected)
      .as("Verify CountryStistics relevant properties")
      .satisfies(
        e ->
          assertThat(e.getName()).as("check name").isEqualTo(actual.getName())
      )
      .satisfies(
        e ->
          assertThat(e.getTotalCount())
            .as("check totalCount")
            .isEqualTo(actual.getTotalCount())
      )
      .satisfies(
        e ->
          assertThat(e.getOnlineCount())
            .as("check onlineCount")
            .isEqualTo(actual.getOnlineCount())
      )
      .satisfies(
        e ->
          assertThat(e.getOfflineCount())
            .as("check offlineCount")
            .isEqualTo(actual.getOfflineCount())
      )
      .satisfies(
        e ->
          assertThat(e.getOtherCount())
            .as("check otherCount")
            .isEqualTo(actual.getOtherCount())
      )
      .satisfies(
        e ->
          assertThat(e.getStatisticDate())
            .as("check statisticDate")
            .isEqualTo(actual.getStatisticDate())
      )
      .satisfies(
        e ->
          assertThat(e.getStatisticTime())
            .as("check statisticTime")
            .isEqualTo(actual.getStatisticTime())
      );
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertCountryStisticsUpdatableRelationshipsEquals(
    CountryStistics expected,
    CountryStistics actual
  ) {}
}
