package com.yuzhi.ainms.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NCEAPStatusAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNCEAPStatusAllPropertiesEquals(
    NCEAPStatus expected,
    NCEAPStatus actual
  ) {
    assertNCEAPStatusAutoGeneratedPropertiesEquals(expected, actual);
    assertNCEAPStatusAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNCEAPStatusAllUpdatablePropertiesEquals(
    NCEAPStatus expected,
    NCEAPStatus actual
  ) {
    assertNCEAPStatusUpdatableFieldsEquals(expected, actual);
    assertNCEAPStatusUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNCEAPStatusAutoGeneratedPropertiesEquals(
    NCEAPStatus expected,
    NCEAPStatus actual
  ) {
    assertThat(expected)
      .as("Verify NCEAPStatus auto generated properties")
      .satisfies(
        e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId())
      );
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNCEAPStatusUpdatableFieldsEquals(
    NCEAPStatus expected,
    NCEAPStatus actual
  ) {
    assertThat(expected)
      .as("Verify NCEAPStatus relevant properties")
      .satisfies(
        e ->
          assertThat(e.getApSn()).as("check apSn").isEqualTo(actual.getApSn())
      )
      .satisfies(
        e ->
          assertThat(e.getApStatus())
            .as("check apStatus")
            .isEqualTo(actual.getApStatus())
      );
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertNCEAPStatusUpdatableRelationshipsEquals(
    NCEAPStatus expected,
    NCEAPStatus actual
  ) {}
}
